"""Interface strings for the site, per language.

English is final. Every other language is a DRAFT and is not published until a
native reader has signed it off (see docs/launch/journal.md in kipster254/novena).
A language is only built when it appears in build.py's LANGS, and only merged
to main after that sign-off is recorded.
"""

STRINGS = {
    "en": {
        "html_lang": "en",
        "og_locale": "en_US",
        "nav_novenas": "Novenas",
        "nav_support": "Support",
        "nav_press": "Press",
        "skip": "Skip to content",
        "home_title": "Novena — pray a novena, nine days at a time",
        "home_description": "A quiet, offline Catholic novena app for Android. Find your saint, pray the novena, and keep your place with a gentle daily reminder. No subscription, no account, no ads.",
        "hero_kicker": "A Catholic novena app for Android",
        "hero_line": "Find your saint. Pray the novena.<br>Nine days, one at a time.",
        "promise_line": "No subscription. No account. No ads. Works offline.",
        "hero_try": "Pray the St. Jude novena here",
        "hero_try_sub": "The full text of all nine days is on this site.",
        "section_what": "What it is",
        "what_body": [
            "A novena is nine days of prayer for one intention. Catholics have prayed them for centuries, and the hard part has never been finding the words. It is remembering on day four.",
            "Novena gives you the full text of each novena, keeps your place, and, if you want one, sends a gentle daily reminder at a time you choose. If you miss a day, your progress stays where it was. There are no streaks to break.",
        ],
        "section_promise": "What to expect",
        "promise_items": [
            ("Your intentions stay on your phone.", "Your intentions, your progress and your reminder times are stored only on your device. There is no account, no server of our own, no analytics and no advertising."),
            ("It works offline.", "Every novena you can read is already on your phone. Airplane mode is fine."),
            ("Every prayer shows its source.", "Tap Sources & attribution on any novena to see where its text comes from."),
            ("No subscription, ever.", "Five novenas are free, with every feature. The rest of the catalog is unlocked with a one-time purchase through Google Play. Nothing renews."),
        ],
        "section_free": "Free in the app",
        "free_intro": "These five English novenas are free, with reminders, dark mode, text sizes and your prayer history. Their full text is also on this site.",
        "free_more": "See all 23 English novenas",
        "section_languages": "Five languages",
        "languages_body": "The app's interface and its novenas are available in English, Spanish, Portuguese (Brazil), Italian and Filipino. Each language has its own catalog of 23 novenas, and the five free novenas differ slightly from one language to another.",
        "section_honest": "The trade-off",
        "honest_body": "Because nothing is stored anywhere but your phone, nothing can be restored if you delete the app. Your purchases come back through Restore Purchases, but your intentions and history do not. There is no backup and no sync, by design.",
        "section_screens": "Inside the app",
        "shot_alts": [
            "The Today screen: a novena to St. Rita of Cascia on day 1 of 9, marked Catching up, with a Pray day one button",
            "A locked novena's page in light mode, with its Sources & attribution link",
            "A day's prayer in dark mode: the end of the day's reflection, the closing prayer, and Mark today's prayer done",
        ],
        "cta_heading": "Pray it with reminders",
        "cta_body": "The app keeps your place and, if you like, reminds you once a day for all nine days.",
        "coming_soon": "Coming soon to Google Play",
        "coming_soon_body": "Novena is not yet publicly available on Google Play. This page will link to it the day it is. There is no iPhone version.",
        "get_it": "Get Novena on Google Play",
        "play_trademark": "Google Play and the Google Play logo are trademarks of Google LLC.",
        "not_affiliated": "Novena is an independent app. It is not affiliated with or endorsed by any diocese, parish or shrine.",
        "footer_privacy": "Privacy",
        "footer_support": "Support",
        "footer_press": "Press",
        "footer_novenas": "Novenas",
        "footer_no_tracking": "This site sets no cookies and loads nothing from anyone else.",
        # Novena pages
        "novenas_title": "Novenas",
        "novenas_description": "All 23 English novenas in the Novena app. Five are free, and their full text is on this site.",
        "novenas_intro": "The English catalog has 23 novenas. Five are free in the app and their full text is here. The rest are part of the one-time unlock, and their pages here give only a summary.",
        "badge_free": "Free",
        "badge_unlock": "In the app",
        "free_full_text": "Full text on this site",
        "for_label": "Intentions",
        "feast_label": "Feast",
        "fixed_label": "Prayed each year from",
        "source_label": "Source",
        "imprimatur_label": "Imprimatur",
        "about_label": "About",
        "about_source": "About this text",
        "how_to": "Pray once a day for nine days: the opening prayer, then the day's reflection, then the closing prayer. Hold one intention through all nine days.",
        "opening_prayer": "Opening prayer",
        "opening_prayer_note": "Pray this at the start of each day.",
        "closing_prayer": "Closing prayer",
        "day": "Day",
        "day_of": "Day {n} of 9",
        "days_nav": "Jump to a day",
        "back_to_top": "Back to the days",
        "in_app_heading": "Pray it with reminders in the app",
        "in_app_body": "The app keeps your place in this novena and, if you like, reminds you once a day at a time you choose. This novena is free in the app, with no account.",
        "summary_note": "This novena is part of the app's one-time unlock, so its text is not published here.",
        "summary_sources": "In the app, tap Sources on this novena to see its full source note.",
        "novena_page_title": "{title} — full text, nine days",
        "novena_page_description": "Pray the {title}: the full text of all nine days, with its source, and a note on where each prayer comes from.",
        "summary_page_description": "{title} in the Novena app for Android: who it is prayed to, what for, and where its text comes from.",
        "saint_label": "Prayed to",
        "other_free": "Other free novenas",
        # Guide
        "nav_guide": "What is a novena?",
        "guide_title": "What is a novena, and how do you pray one?",
        "guide_description": "A novena is nine days of prayer for one intention. Where the practice comes from, how to pray one, and five novenas you can start today.",
        "guide_sections": [
            ("Nine days, one intention", [
                "A novena is a prayer said on nine days in a row, usually for one intention: a need you are carrying, a person you love, a decision you have to make, or thanksgiving. The word comes from the Latin <i lang=\"la\">novem</i>, nine.",
                "The 1911 <i>Catholic Encyclopedia</i> defines it as “a nine days' private or public devotion in the Catholic Church to obtain special graces”, and notes that it is “permitted and even recommended by ecclesiastical authority, but still has no proper and fully set place in the liturgy of the Church.” A novena is a devotion, not a sacrament and not a formula that guarantees an outcome.",
            ]),
            ("Where the nine days come from", [
                "The same article calls the first Pentecost “the best model and example” of a novena. After the Ascension, the apostles returned to Jerusalem and waited in the upper room for the Holy Spirit. The Acts of the Apostles says: “All these were persevering with one mind in prayer with the women, and Mary the mother of Jesus, and with his brethren” (Acts 1:14, Douay-Rheims). St. Jude is one of the apostles named in that room (Acts 1:13).",
                "Many novenas are prayed in the nine days before a saint's feast, so that the last day falls on the eve of the feast or on the feast itself. Others are prayed at any time of year, whenever the need arises.",
            ]),
            ("How to pray one", [
                "Choose one intention and hold it for all nine days. You do not need to write it down or tell anyone.",
                "Pray once a day, at roughly the same time if you can. Each day usually has an opening prayer, a short reading or reflection, and a closing prayer. It takes a few minutes.",
                "If you miss a day, pick up where you left off. The practice is faithfulness, not perfection.",
                "At the end, many people give thanks whatever the outcome, and some begin another novena.",
            ]),
        ],
        "guide_free_h": "Five novenas you can pray today",
        "guide_free_intro": "The full text of each of these is on this site, and they are free in the app.",
        "guide_source": "Sources: “Novena”, Joseph Hilgers, <i>The Catholic Encyclopedia</i>, vol. 11 (1911, public domain), newadvent.org/cathen/11141b.htm; Acts 1:12–14, Douay-Rheims Bible (public domain). Both read 23 September 2026.",
        # Parish
        "parish_title": "Novena: pray a novena, nine days at a time",
        "parish_description": "You found Novena through a card or a bulletin. Pray the St. Jude novena here, free, or see the five free novenas.",
        "parish_intro": "You found this through a card, poster or bulletin. Welcome. Novena is an independent app; it is not run by or affiliated with any parish or diocese, and whoever shared this card did so as a friend.",
        "parish_body": "A novena is nine days of prayer for one intention. You can pray one right here, on this site: every day's full text is on the page. If you want help remembering, the Novena app for Android keeps your place and can remind you once a day. There is no account, no ads, and nothing you pray leaves your phone.",
        "parish_start": "Start the St. Jude novena, day 1",
        "parish_all": "The five free novenas",
        "kit_title": "Parish kit",
        "kit_description": "A printable poster, QR cards and a bulletin insert for sharing Novena in a parish, and a short note for a priest or ministry lead.",
        "kit_intro": "For anyone who wants to share Novena in their parish. Print this page: it comes out as a poster, a sheet of cards and a bulletin insert. Please ask your parish office before putting anything up or in the bulletin.",
        "kit_not_live": "Do not print yet. The QR code points to getnovena.app, which is not live yet. This notice disappears when it is.",
        "kit_bulletin_h": "Bulletin insert (about 80 words)",
        "kit_bulletin": "Praying a novena? A novena is nine days of prayer for one intention. Novena, a free-to-start app for Android, holds your place and can send one gentle reminder a day, so day four doesn't slip. It has no ads, no account and no subscription, and what you pray stays on your phone. The full St. Jude novena is at getnovena.app. (Novena is an independent app and is not affiliated with this parish.)",
        "kit_note_h": "A note to hand to a priest or ministry lead",
        "kit_note": [
            "Father, or dear friend in ministry,",
            "I have been using a small Catholic prayer app called Novena and wondered whether it might be worth a line in the bulletin. It helps people pray a novena for all nine days, with a gentle daily reminder. It has no ads, no account and no subscription, and nothing a person prays is sent anywhere. Every prayer in it shows its source.",
            "It is an independent app, not affiliated with any diocese. The full text of the St. Jude novena is free at getnovena.app, if you would like to read it first.",
            "Thank you for considering it.",
        ],
        "kit_poster_line": "Pray a novena,<br>nine days at a time.",
        "kit_poster_sub": "The St. Jude novena, on your phone. Scan to begin.",
        "kit_card_line": "Pray a novena, nine days at a time.",
        "kit_card_sub": "Scan to pray the St. Jude novena",
        "kit_footer": "Novena is an independent app for Android. Not affiliated with any parish, diocese or shrine.",
        # Support
        "support_title": "Support",
        "support_description": "Help with the Novena app: restoring a purchase, reminders, and what happens to your data.",
        "support_contact_h": "Contact",
        "support_contact": "Write to <a href=\"mailto:hello@getnovena.app\">hello@getnovena.app</a>. Please do not send us your prayer intentions; we do not need them to help you, and the app is designed so that we never see them.",
        "support_faq": [
            ("I bought an unlock. How do I get it back on a new phone or after reinstalling?",
             "Open Settings in the app and tap <strong>Restore Purchases</strong>, or tap it on the unlock screen. The app asks Google Play which unlocks your Google account owns and brings them back. Use the same Google account you bought with. If it says it couldn't reach the store, check your connection and try again."),
            ("Why can't you restore my intentions and prayer history?",
             "Because we never have them. Everything you write or pray in Novena is stored only on your phone. There is no account, no server and no cloud backup, so deleting the app, or moving to a new phone, starts you fresh. Your purchases are the exception: Google Play keeps a record of those, so Restore Purchases works."),
            ("My reminder didn't arrive.",
             "Reminders are scheduled on your phone by your phone. Some Android phones stop apps' notifications to save battery. In Android's settings, allow notifications for Novena and exempt it from battery optimisation. Missing a day never resets your progress; the app offers to pick up where you left off."),
            ("Which novenas are free?",
             "Five in each language, with every feature. In English: St. Jude, St. Joseph, St. Anthony of Padua, the Holy Spirit and Our Lady, Undoer of Knots. The free set differs slightly by language. You can filter to free novenas inside the app."),
            ("Is it a subscription?",
             "No. The rest of the catalog is unlocked with a one-time purchase through Google Play. Nothing renews. Google Play shows the price in your currency before you buy."),
            ("Is there an iPhone version?",
             "No. Novena is only on Android."),
            ("Where do the prayers come from?",
             "Each novena shows its source in the app, under Sources & attribution. Some texts are traditional prayers; many reflections were written for the app. Novena is not endorsed by any diocese, parish or shrine."),
            ("Does the app collect any data?",
             "The app has no analytics, no advertising and no tracking, and your intentions and prayers are never sent anywhere. It does go online for two things: each time it opens it checks Expo's update service for new content, and it asks Google Play which purchases you own, at launch, on the unlock screen, and when you buy or restore. The <a href=\"{privacy}\">privacy policy</a> has the details."),
        ],
        "support_rate": "If Novena helps you, a rating on Google Play helps others find it. In the app: Settings, then Rate Novena. The app never asks you to rate it.",
        # Press
        "press_title": "Press kit",
        "press_description": "Logos, screenshots and descriptions of the Novena app, free to use when writing about it.",
        "press_intro": "Everything here may be used to write about Novena. Please keep the images unaltered.",
        "press_one_sentence_h": "In one sentence",
        "press_one_sentence": "Novena is a private, offline Catholic novena app for Android that helps you pray a nine-day novena with one gentle daily reminder, with no subscription, no account and no ads.",
        "press_paragraph_h": "In a paragraph",
        "press_paragraph": "Novena is a Catholic prayer app for Android built around one practice: the novena, nine days of prayer for one intention. It carries 23 novenas in each of five languages (English, Spanish, Brazilian Portuguese, Italian and Filipino), each language with its own catalog. Five novenas in each language are free with every feature, and the rest are a one-time unlock, never a subscription. It works offline, needs no account, shows no ads, and keeps everything a person prays on their own phone: there is no server of its own and no analytics. Every prayer shows its source.",
        "press_facts_h": "Facts",
        "press_facts": [
            ("Platform", "Android. Coming soon to Google Play; not yet publicly available. There is no iPhone version."),
            ("Package", "com.arapleting.novena"),
            ("Languages", "English, Spanish, Portuguese (Brazil), Italian, Filipino"),
            ("Catalog", "23 novenas per language; 5 free in each"),
            ("Price model", "Free to start; one-time unlock; no subscription"),
            ("Data", "No account, no analytics, no ads; prayers and intentions stay on the phone"),
            ("Name", "Novena, said noh-VEE-nuh in English"),
            ("Contact", "<a href=\"mailto:hello@getnovena.app\">hello@getnovena.app</a>"),
        ],
        "press_assets_h": "Images",
        "press_icon": "App icon, 512 × 512 PNG",
        "press_feature": "Feature graphic, 1024 × 500 PNG",
        "press_shot": "Screenshot, 1080 × 1920 PNG",
        "press_brand_h": "Using the name",
        "press_do_h": "Please do",
        "press_do": [
            "Write the name as <strong>Novena</strong>, one word, capital N.",
            "Describe it as an independent app.",
            "Say “one-time unlock” or “no subscription” rather than quoting a price; prices vary by country and Google Play shows the current one.",
        ],
        "press_dont_h": "Please don't",
        "press_dont": [
            "Say or imply that Novena is endorsed by the Church, a diocese, a parish or a shrine. It isn't.",
            "Describe it as available on iPhone. It isn't.",
            "Crop, recolour or redraw the icon.",
        ],
        # 404
        "notfound_title": "Page not found",
        "notfound_body": "This page doesn't exist, or it has moved.",
        "notfound_home": "Go to the home page",
        "notfound_novenas": "See the novenas",
    },
}


# es: AWAITING NATIVE READ (drafted 2026-09-23). This branch must not merge
# until a native reader signs off in kipster254/novena docs/launch/journal.md.
STRINGS['es'] = {'html_lang': 'es', 'og_locale': 'es_LA', 'nav_novenas': 'Novenas', 'nav_support': 'Ayuda', 'nav_press': 'Prensa', 'skip': 'Saltar al contenido', 'home_title': 'Novena — reza una novena, nueve días, uno a la vez', 'home_description': 'Una app católica de novenas para Android, tranquila y sin conexión. Encuentra a tu santo, reza la novena y no pierdas el hilo con un suave recordatorio diario. Sin suscripción, sin cuenta, sin anuncios.', 'hero_kicker': 'Una app católica de novenas para Android', 'hero_line': 'Encuentra a tu santo. Reza la novena.<br>Nueve días, uno a la vez.', 'promise_line': 'Sin suscripción. Sin cuenta. Sin anuncios. Funciona sin conexión.', 'hero_try': 'Reza aquí la novena a San Judas Tadeo', 'hero_try_sub': 'El texto completo de los nueve días está en este sitio.', 'section_what': 'Qué es', 'what_body': ['Una novena son nueve días de oración por una sola intención. Los católicos las rezan desde hace siglos, y lo difícil nunca ha sido encontrar las palabras, sino acordarse el cuarto día.', 'Novena te da el texto completo de cada novena, guarda el punto en el que vas y, si quieres, te envía un suave recordatorio diario a la hora que elijas. Si te saltas un día, tu avance se queda donde estaba. No hay rachas que romper.'], 'section_promise': 'Qué puedes esperar', 'promise_items': [('Tus intenciones se quedan en tu teléfono.', 'Tus intenciones, tu avance y las horas de tus recordatorios se guardan solo en tu dispositivo. No hay cuenta, ni servidor propio, ni analítica, ni publicidad.'), ('Funciona sin conexión.', 'Todas las novenas que puedes leer ya están en tu teléfono. El modo avión no es problema.'), ('Cada oración muestra su fuente.', 'Toca Fuentes y atribución en cualquier novena para ver de dónde viene su texto.'), ('Nunca habrá suscripción.', 'Cinco novenas son gratuitas, con todas las funciones. El resto del catálogo se desbloquea con una compra única a través de Google Play. Nada se renueva.')], 'section_free': 'Gratis en la app', 'free_intro': 'Estas cinco novenas en español son gratuitas, con recordatorios, modo oscuro, tamaños de texto y tu historial de oración. Su texto completo también está en este sitio.', 'free_more': 'Ver las 23 novenas en español', 'section_languages': 'Cinco idiomas', 'languages_body': 'La interfaz de la app y sus novenas están disponibles en inglés, español, portugués (Brasil), italiano y filipino. Cada idioma tiene su propio catálogo de 23 novenas, y las cinco novenas gratuitas cambian un poco de un idioma a otro.', 'section_honest': 'La contrapartida', 'honest_body': 'Como nada se guarda fuera de tu teléfono, nada se puede recuperar si borras la app. Tus compras vuelven con Restaurar compras, pero tus intenciones y tu historial no. No hay copia de seguridad ni sincronización, a propósito.', 'section_screens': 'Dentro de la app', 'shot_alts': ['La pantalla Hoy (en inglés): una novena a Santa Rita de Casia en el día 1 de 9, marcada «Catching up» (Poniéndote al día), con el botón «Pray day one» (Rezar el día uno)', 'La página de una novena bloqueada en modo claro (en inglés), con su enlace «Sources & attribution» (Fuentes y atribución)', "La oración de un día en modo oscuro (en inglés): el final de la reflexión del día, la oración final y el botón «Mark today's prayer done» (Marcar la oración de hoy como completada)"], 'cta_heading': 'Rézala con recordatorios', 'cta_body': 'La app guarda el punto en el que vas y, si quieres, te lo recuerda una vez al día durante los nueve días.', 'coming_soon': 'Próximamente en Google Play', 'coming_soon_body': 'Novena todavía no está disponible públicamente en Google Play. Esta página enlazará a la app el día en que lo esté. No existe versión para iPhone.', 'get_it': 'Disponible en Google Play', 'play_trademark': 'Google Play y el logotipo de Google Play son marcas de Google LLC.', 'not_affiliated': 'Novena es una app independiente. No está afiliada a ninguna diócesis, parroquia ni santuario, ni cuenta con su respaldo.', 'footer_privacy': 'Privacidad', 'footer_support': 'Ayuda', 'footer_press': 'Prensa', 'footer_novenas': 'Novenas', 'footer_no_tracking': 'Este sitio no usa cookies ni carga nada de terceros.', 'novenas_title': 'Novenas', 'novenas_description': 'Las 23 novenas en español de la app Novena. Cinco son gratuitas, y su texto completo está en este sitio.', 'novenas_intro': 'El catálogo en español tiene 23 novenas. Cinco son gratuitas en la app y su texto completo está aquí. Las demás forman parte del desbloqueo único, y sus páginas aquí muestran solo un resumen.', 'badge_free': 'Gratis', 'badge_unlock': 'En la app', 'free_full_text': 'Texto completo en este sitio', 'for_label': 'Intenciones', 'feast_label': 'Fiesta', 'fixed_label': 'Se reza cada año a partir del', 'source_label': 'Fuente', 'imprimatur_label': 'Imprimatur', 'about_label': 'Acerca de', 'about_source': 'Acerca de este texto', 'how_to': 'Reza una vez al día durante nueve días: la oración inicial, luego la reflexión del día y después la oración final. Mantén una sola intención durante los nueve días.', 'opening_prayer': 'Oración inicial', 'opening_prayer_note': 'Rézala al comienzo de cada día.', 'closing_prayer': 'Oración final', 'day': 'Día', 'day_of': 'Día {n} de 9', 'days_nav': 'Ir a un día', 'back_to_top': 'Volver a los días', 'in_app_heading': 'Rézala con recordatorios en la app', 'in_app_body': 'La app guarda el punto en el que vas en esta novena y, si quieres, te lo recuerda una vez al día a la hora que elijas. Esta novena es gratuita en la app, sin cuenta.', 'summary_note': 'Esta novena forma parte del desbloqueo único de la app, por eso su texto no se publica aquí.', 'summary_sources': 'En la app, toca Fuentes en esta novena para ver su nota de fuentes completa.', 'novena_page_title': '{title} — texto completo, nueve días', 'novena_page_description': 'Reza la {title}: el texto completo de los nueve días, con su fuente y una nota sobre el origen de cada oración.', 'summary_page_description': '{title} en la app Novena para Android: a quién se reza, por qué intenciones y de dónde viene su texto.', 'saint_label': 'Se reza a', 'other_free': 'Otras novenas gratuitas', 'nav_guide': '¿Qué es una novena?', 'guide_title': '¿Qué es una novena y cómo se reza?', 'guide_description': 'Una novena son nueve días de oración por una sola intención. De dónde viene esta práctica, cómo se reza y cinco novenas que puedes empezar hoy.', 'guide_sections': [('Nueve días, una intención', ['Una novena es una oración que se reza nueve días seguidos, normalmente por una sola intención: una necesidad que llevas contigo, una persona a quien quieres, una decisión que tienes que tomar o una acción de gracias. La palabra viene del latín <i lang="la">novem</i>, nueve.', 'La <i>Catholic Encyclopedia</i> de 1911 la define como «una devoción de nueve días, privada o pública, en la Iglesia católica, para obtener gracias especiales», y señala que está «permitida e incluso recomendada por la autoridad eclesiástica, pero todavía no tiene un lugar propio y plenamente establecido en la liturgia de la Iglesia» (traducción nuestra). Una novena es una devoción, no un sacramento ni una fórmula que garantice un resultado.']), ('De dónde vienen los nueve días', ['El mismo artículo llama al primer Pentecostés «el mejor modelo y ejemplo» de una novena (traducción nuestra). Después de la Ascensión, los apóstoles volvieron a Jerusalén y esperaron al Espíritu Santo en la habitación alta. Los Hechos de los Apóstoles dicen: «Todos los cuales, animados de un mismo espíritu, perseveraban juntos en oración con las mujeres piadosas, y con María la madre de Jesús, y con los hermanos o parientes de este Señor» (Hechos 1,14, versión de Torres Amat). San Judas es uno de los apóstoles nombrados en aquella habitación: «Judas hermano de Santiago» (Hechos 1,13).', 'Muchas novenas se rezan en los nueve días anteriores a la fiesta de un santo, de modo que el último día cae en la víspera de la fiesta o en la fiesta misma. Otras se rezan en cualquier época del año, cuando surge la necesidad.']), ('Cómo se reza', ['Elige una intención y mantenla durante los nueve días. No necesitas escribirla ni contársela a nadie.', 'Reza una vez al día, más o menos a la misma hora si puedes. Cada día suele tener una oración inicial, una lectura o reflexión breve y una oración final. Lleva unos minutos.', 'Si te saltas un día, sigue donde lo dejaste. La práctica consiste en la fidelidad, no en la perfección.', 'Al terminar, muchas personas dan gracias sea cual sea el resultado, y algunas comienzan otra novena.'])], 'guide_free_h': 'Cinco novenas que puedes rezar hoy', 'guide_free_intro': 'El texto completo de cada una está en este sitio, y son gratuitas en la app.', 'guide_source': 'Fuentes: «Novena», Joseph Hilgers, <i>The Catholic Encyclopedia</i>, vol. 11 (1911, dominio público), newadvent.org/cathen/11141b.htm, citado en traducción nuestra; Hechos 1,12-14, Félix Torres Amat, «La Sagrada Biblia», tomo XIV (1825, dominio público), con la ortografía actualizada. Ambas consultadas el 23 de septiembre de 2026.', 'parish_title': 'Novena: reza una novena, nueve días, uno a la vez', 'parish_description': 'Conociste Novena por una tarjeta o un boletín. Reza aquí la novena a San Judas Tadeo, gratis, o mira las cinco novenas gratuitas.', 'parish_intro': 'Llegaste aquí por una tarjeta, un cartel o un boletín. Bienvenido. Novena es una app independiente; no la gestiona ninguna parroquia ni diócesis ni está afiliada a ellas, y quien compartió esta tarjeta lo hizo como amigo.', 'parish_body': 'Una novena son nueve días de oración por una sola intención. Puedes rezarla aquí mismo, en este sitio: el texto completo de cada día está en la página. Si quieres ayuda para acordarte, la app Novena para Android guarda el punto en el que vas y puede recordártelo una vez al día. No hay cuenta ni anuncios, y nada de lo que rezas sale de tu teléfono.', 'parish_start': 'Empezar la novena a San Judas Tadeo, día 1', 'parish_all': 'Las cinco novenas gratuitas', 'kit_title': 'Material para parroquias', 'kit_description': 'Un cartel para imprimir, tarjetas con código QR y un texto para el boletín para compartir Novena en una parroquia, y una nota breve para un sacerdote o responsable de pastoral.', 'kit_intro': 'Para quien quiera compartir Novena en su parroquia. Imprime esta página: sale como un cartel, una hoja de tarjetas y un texto para el boletín. Antes de colgar algo o de ponerlo en el boletín, pregunta en la oficina parroquial.', 'kit_not_live': 'Todavía no lo imprimas. El código QR apunta a getnovena.app, que aún no está en línea. Este aviso desaparecerá cuando lo esté.', 'kit_bulletin_h': 'Texto para el boletín (unas 80 palabras)', 'kit_bulletin': '¿Rezas novenas? Una novena son nueve días de oración por una sola intención. Novena, una app para Android que puedes empezar a usar gratis, guarda el punto en el que vas y puede enviarte un suave recordatorio al día, para que el cuarto día no se te escape. No tiene anuncios, ni cuenta, ni suscripción, y lo que rezas se queda en tu teléfono. La novena completa a San Judas Tadeo está en getnovena.app/es. (Novena es una app independiente y no está afiliada a esta parroquia.)', 'kit_note_h': 'Una nota para entregar a un sacerdote o responsable de pastoral', 'kit_note': ['Padre, o querido hermano en el ministerio:', 'He estado usando una pequeña app católica de oración llamada Novena y me preguntaba si valdría la pena mencionarla en el boletín. Ayuda a rezar una novena durante los nueve días, con un suave recordatorio diario. No tiene anuncios, ni cuenta, ni suscripción, y nada de lo que alguien reza se envía a ninguna parte. Cada oración muestra su fuente.', 'Es una app independiente, no afiliada a ninguna diócesis. El texto completo de la novena a San Judas Tadeo está gratis en getnovena.app/es, por si quiere leerlo antes.', 'Gracias por considerarlo.'], 'kit_poster_line': 'Reza una novena,<br>nueve días, uno a la vez.', 'kit_poster_sub': 'La novena a San Judas Tadeo, en tu teléfono. Escanea para empezar.', 'kit_card_line': 'Reza una novena, nueve días, uno a la vez.', 'kit_card_sub': 'Escanea para rezar la novena a San Judas Tadeo', 'kit_footer': 'Novena es una app independiente para Android. No está afiliada a ninguna parroquia, diócesis ni santuario.', 'support_title': 'Ayuda', 'support_description': 'Ayuda con la app Novena: restaurar una compra, los recordatorios y qué pasa con tus datos.', 'support_contact_h': 'Contacto', 'support_contact': 'Escribe a <a href="mailto:hello@getnovena.app">hello@getnovena.app</a>. Por favor, no nos envíes tus intenciones de oración; no las necesitamos para ayudarte, y la app está diseñada para que nunca las veamos.', 'support_faq': [('Compré un desbloqueo. ¿Cómo lo recupero en un teléfono nuevo o después de reinstalar la app?', 'Abre Ajustes en la app y toca <strong>Restaurar compras</strong>, o tócalo en la pantalla de desbloqueo. La app le pregunta a Google Play qué desbloqueos tiene tu cuenta de Google y los recupera. Usa la misma cuenta de Google con la que compraste. Si dice que no pudo conectar con la tienda, revisa tu conexión y vuelve a intentarlo.'), ('¿Por qué no pueden recuperar mis intenciones y mi historial de oración?', 'Porque nunca los tenemos. Todo lo que escribes o rezas en Novena se guarda solo en tu teléfono. No hay cuenta, ni servidor, ni copia de seguridad en la nube, así que si borras la app o cambias de teléfono, empiezas de cero. Tus compras son la excepción: Google Play guarda un registro de ellas, por eso Restaurar compras funciona.'), ('No me llegó el recordatorio.', 'Los recordatorios los programa tu propio teléfono. Algunos teléfonos Android detienen las notificaciones de las apps para ahorrar batería. En los ajustes de Android, permite las notificaciones de Novena y exclúyela de la optimización de batería. Saltarte un día nunca reinicia tu avance; la app te ofrece seguir donde lo dejaste.'), ('¿Qué novenas son gratuitas?', 'Cinco en cada idioma, con todas las funciones. En español: San Judas Tadeo, San José, San Antonio de Padua, María Desatanudos y la Novena de Entrega y Confianza en la Divina Providencia (reflexión original de nueve días sobre el abandono en Dios; no es la novena del padre Dolindo Ruotolo). El conjunto gratuito cambia un poco de un idioma a otro. En la app puedes filtrar las novenas gratuitas.'), ('¿Es una suscripción?', 'No. El resto del catálogo se desbloquea con una compra única a través de Google Play. Nada se renueva. Google Play te muestra el precio en tu moneda antes de comprar.'), ('¿Hay versión para iPhone?', 'No. Novena solo está en Android.'), ('¿De dónde vienen las oraciones?', 'Cada novena muestra su fuente en la app, en Fuentes y atribución. Algunos textos son oraciones tradicionales; muchas reflexiones se escribieron para la app. Novena no cuenta con el respaldo de ninguna diócesis, parroquia ni santuario.'), ('¿La app recopila datos?', 'La app no tiene analítica, ni publicidad, ni rastreo, y tus intenciones y oraciones nunca se envían a ninguna parte. Solo se conecta a internet para dos cosas: cada vez que se abre, consulta el servicio de actualizaciones de Expo para ver si hay contenido nuevo, y le pregunta a Google Play qué compras tienes, al iniciarse, en la pantalla de desbloqueo y cuando compras o restauras. La <a href="{privacy}">política de privacidad</a> tiene los detalles.')], 'support_rate': 'Si Novena te ayuda, una calificación en Google Play ayuda a que otros la encuentren. En la app: Ajustes y luego Calificar Novena. La app nunca te pide que la califiques.', 'press_title': 'Kit de prensa', 'press_description': 'Logotipos, capturas de pantalla y descripciones de la app Novena, de uso libre para escribir sobre ella.', 'press_intro': 'Todo lo que hay aquí se puede usar para escribir sobre Novena. Por favor, no modifiques las imágenes.', 'press_one_sentence_h': 'En una frase', 'press_one_sentence': 'Novena es una app católica de novenas para Android, privada y sin conexión, que te ayuda a rezar una novena de nueve días con un suave recordatorio diario, sin suscripción, sin cuenta y sin anuncios.', 'press_paragraph_h': 'En un párrafo', 'press_paragraph': 'Novena es una app católica de oración para Android construida en torno a una sola práctica: la novena, nueve días de oración por una sola intención. Incluye 23 novenas en cada uno de sus cinco idiomas (inglés, español, portugués de Brasil, italiano y filipino), cada idioma con su propio catálogo. Cinco novenas de cada idioma son gratuitas con todas las funciones, y las demás se obtienen con un desbloqueo único, nunca con una suscripción. Funciona sin conexión, no necesita cuenta, no muestra anuncios y guarda todo lo que una persona reza en su propio teléfono: no tiene servidor propio ni analítica. Cada oración muestra su fuente.', 'press_facts_h': 'Datos', 'press_facts': [('Plataforma', 'Android. Próximamente en Google Play; todavía no disponible públicamente. No existe versión para iPhone.'), ('Paquete', 'com.arapleting.novena'), ('Idiomas', 'inglés, español, portugués (Brasil), italiano, filipino'), ('Catálogo', '23 novenas por idioma; 5 gratuitas en cada uno'), ('Modelo de precio', 'Gratis para empezar; desbloqueo único; sin suscripción'), ('Datos', 'Sin cuenta, sin analítica, sin anuncios; las oraciones y las intenciones se quedan en el teléfono'), ('Nombre', 'Novena, igual que la palabra en español'), ('Contacto', '<a href="mailto:hello@getnovena.app">hello@getnovena.app</a>')], 'press_assets_h': 'Imágenes', 'press_icon': 'Icono de la app, PNG de 512 × 512', 'press_feature': 'Gráfico destacado, PNG de 1024 × 500', 'press_shot': 'Captura de pantalla, PNG de 1080 × 1920', 'press_brand_h': 'Cómo usar el nombre', 'press_do_h': 'Por favor', 'press_do': ['Escribe el nombre como <strong>Novena</strong>, en una sola palabra y con N mayúscula.', 'Descríbela como una app independiente.', 'Di «desbloqueo único» o «sin suscripción» en lugar de citar un precio; los precios varían según el país y Google Play muestra el vigente.'], 'press_dont_h': 'Por favor, no', 'press_dont': ['Digas ni insinúes que Novena cuenta con el respaldo de la Iglesia, una diócesis, una parroquia o un santuario. No es así.', 'La describas como disponible en iPhone. No lo está.', 'Recortes, cambies el color ni redibujes el icono.'], 'notfound_title': 'Página no encontrada', 'notfound_body': 'Esta página no existe o se ha movido.', 'notfound_home': 'Ir a la página de inicio', 'notfound_novenas': 'Ver las novenas'}
