"""Interface strings for the site, per language.

English is final. Every other language is a DRAFT and is not published until a
native reader has signed it off (see docs/launch/journal.md in kipster254/novena).
A language is only built when it appears in build.py's LANGS, and only merged
to main after that sign-off is recorded.
"""

STRINGS = {
    "en": {
        "html_lang": "en",
        "og_locale": "en_US",
        "nav_novenas": "Novenas",
        "nav_support": "Support",
        "nav_press": "Press",
        "skip": "Skip to content",
        "home_title": "Novena — pray a novena, nine days at a time",
        "home_description": "A quiet, offline Catholic novena app for Android. Find your saint, pray the novena, and keep your place with a gentle daily reminder. No subscription, no account, no ads.",
        "hero_kicker": "A Catholic novena app for Android",
        "hero_line": "Find your saint. Pray the novena.<br>Nine days, one at a time.",
        "promise_line": "No subscription. No account. No ads. Works offline.",
        "hero_try": "Pray the St. Jude novena here",
        "hero_try_sub": "The full text of all nine days is on this site.",
        "section_what": "What it is",
        "what_body": [
            "A novena is nine days of prayer for one intention. Catholics have prayed them for centuries, and the hard part has never been finding the words. It is remembering on day four.",
            "Novena gives you the full text of each novena, keeps your place, and, if you want one, sends a gentle daily reminder at a time you choose. If you miss a day, your progress stays where it was. There are no streaks to break.",
        ],
        "section_promise": "What to expect",
        "promise_items": [
            ("Your intentions stay on your phone.", "Your intentions, your progress and your reminder times are stored only on your device. There is no account, no server of our own, no analytics and no advertising."),
            ("It works offline.", "Every novena you can read is already on your phone. Airplane mode is fine."),
            ("Every prayer shows its source.", "Tap Sources & attribution on any novena to see where its text comes from."),
            ("No subscription, ever.", "Five novenas are free, with every feature. The rest of the catalog is unlocked with a one-time purchase through Google Play. Nothing renews."),
        ],
        "section_free": "Free in the app",
        "free_intro": "These five English novenas are free, with reminders, dark mode, text sizes and your prayer history. Their full text is also on this site.",
        "free_more": "See all 23 English novenas",
        "section_languages": "Five languages",
        "languages_body": "The app's interface and its novenas are available in English, Spanish, Portuguese (Brazil), Italian and Filipino. Each language has its own catalog of 23 novenas, and the five free novenas differ slightly from one language to another.",
        "section_honest": "The trade-off",
        "honest_body": "Because nothing is stored anywhere but your phone, nothing can be restored if you delete the app. Your purchases come back through Restore Purchases, but your intentions and history do not. There is no backup and no sync, by design.",
        "section_screens": "Inside the app",
        "shot_alts": [
            "The Today screen: a novena to St. Rita of Cascia on day 1 of 9, marked Catching up, with a Pray day one button",
            "A locked novena's page in light mode, with its Sources & attribution link",
            "A day's prayer in dark mode: the end of the day's reflection, the closing prayer, and Mark today's prayer done",
        ],
        "cta_heading": "Pray it with reminders",
        "cta_body": "The app keeps your place and, if you like, reminds you once a day for all nine days.",
        "coming_soon": "Coming soon to Google Play",
        "coming_soon_body": "Novena is not yet publicly available on Google Play. This page will link to it the day it is. There is no iPhone version.",
        "get_it": "Get Novena on Google Play",
        "play_trademark": "Google Play and the Google Play logo are trademarks of Google LLC.",
        "not_affiliated": "Novena is an independent app. It is not affiliated with or endorsed by any diocese, parish or shrine.",
        "footer_privacy": "Privacy",
        "footer_support": "Support",
        "footer_press": "Press",
        "footer_novenas": "Novenas",
        "footer_no_tracking": "This site sets no cookies and loads nothing from anyone else. It is hosted on GitHub Pages, which, like any web host, logs visitors' IP addresses for security.",
        # Novena pages
        "novenas_title": "Novenas",
        "novenas_description": "All 23 English novenas in the Novena app. Five are free, and their full text is on this site.",
        "novenas_intro": "The English catalog has 23 novenas. Five are free in the app and their full text is here. The rest are part of the one-time unlock, and their pages here give only a summary.",
        "badge_free": "Free",
        "badge_unlock": "In the app",
        "free_full_text": "Full text on this site",
        "for_label": "Intentions",
        "feast_label": "Feast",
        "fixed_label": "Prayed each year from",
        "source_label": "Source",
        "imprimatur_label": "Imprimatur",
        "about_label": "About",
        "about_source": "About this text",
        "how_to": "Pray once a day for nine days: the opening prayer, then the day's reflection, then the closing prayer. Hold one intention through all nine days.",
        "opening_prayer": "Opening prayer",
        "opening_prayer_note": "Pray this at the start of each day.",
        "closing_prayer": "Closing prayer",
        "day": "Day",
        "day_of": "Day {n} of 9",
        "days_nav": "Jump to a day",
        "back_to_top": "Back to the days",
        "in_app_heading": "Pray it with reminders in the app",
        "in_app_body": "The app keeps your place in this novena and, if you like, reminds you once a day at a time you choose. This novena is free in the app, with no account.",
        "summary_note": "This novena is part of the app's one-time unlock, so its text is not published here.",
        "summary_sources": "In the app, tap Sources on this novena to see its full source note.",
        "novena_page_title": "{title} — full text, nine days",
        "novena_page_description": "Pray the {title}: the full text of all nine days, with its source, and a note on where each prayer comes from.",
        "summary_page_description": "{title} in the Novena app for Android: who it is prayed to, what for, and where its text comes from.",
        "saint_label": "Prayed to",
        "other_free": "Other free novenas",
        # Guide
        "nav_guide": "What is a novena?",
        "guide_title": "What is a novena, and how do you pray one?",
        "guide_description": "A novena is nine days of prayer for one intention. Where the practice comes from, how to pray one, and five novenas you can start today.",
        "guide_sections": [
            ("Nine days, one intention", [
                "A novena is a prayer said on nine days in a row, usually for one intention: a need you are carrying, a person you love, a decision you have to make, or thanksgiving. The word comes from the Latin <i lang=\"la\">novem</i>, nine.",
                "The 1911 <i>Catholic Encyclopedia</i> defines it as “a nine days' private or public devotion in the Catholic Church to obtain special graces”, and notes that it is “permitted and even recommended by ecclesiastical authority, but still has no proper and fully set place in the liturgy of the Church.” A novena is a devotion, not a sacrament and not a formula that guarantees an outcome.",
            ]),
            ("Where the nine days come from", [
                "The same article calls the first Pentecost “the best model and example” of a novena. After the Ascension, the apostles returned to Jerusalem and waited in the upper room for the Holy Spirit. The Acts of the Apostles says: “All these were persevering with one mind in prayer with the women, and Mary the mother of Jesus, and with his brethren” (Acts 1:14, Douay-Rheims). St. Jude is one of the apostles named in that room (Acts 1:13).",
                "Many novenas are prayed in the nine days before a saint's feast, so that the last day falls on the eve of the feast or on the feast itself. Others are prayed at any time of year, whenever the need arises.",
            ]),
            ("How to pray one", [
                "Choose one intention and hold it for all nine days. You do not need to write it down or tell anyone.",
                "Pray once a day, at roughly the same time if you can. Each day usually has an opening prayer, a short reading or reflection, and a closing prayer. It takes a few minutes.",
                "If you miss a day, pick up where you left off. The practice is faithfulness, not perfection.",
                "At the end, many people give thanks whatever the outcome, and some begin another novena.",
            ]),
        ],
        "guide_free_h": "Five novenas you can pray today",
        "guide_free_intro": "The full text of each of these is on this site, and they are free in the app.",
        "guide_source": "Sources: “Novena”, Joseph Hilgers, <i>The Catholic Encyclopedia</i>, vol. 11 (1911, public domain), newadvent.org/cathen/11141b.htm; Acts 1:12–14, Douay-Rheims Bible (public domain). Both read 23 September 2026.",
        # Parish
        "parish_title": "Novena: pray a novena, nine days at a time",
        "parish_description": "You found Novena through a card or a bulletin. Pray the St. Jude novena here, free, or see the five free novenas.",
        "parish_intro": "You found this through a card, poster or bulletin. Welcome. Novena is an independent app; it is not run by or affiliated with any parish or diocese, and whoever shared this card did so as a friend.",
        "parish_body": "A novena is nine days of prayer for one intention. You can pray one right here, on this site: every day's full text is on the page. If you want help remembering, the Novena app for Android keeps your place and can remind you once a day. There is no account, no ads, and nothing you pray leaves your phone.",
        "parish_start": "Start the St. Jude novena, day 1",
        "parish_all": "The five free novenas",
        "kit_title": "Parish kit",
        "kit_description": "A printable poster, QR cards and a bulletin insert for sharing Novena in a parish, and a short note for a priest or ministry lead.",
        "kit_intro": "For anyone who wants to share Novena in their parish. Print this page: it comes out as a poster, a sheet of cards and a bulletin insert. Please ask your parish office before putting anything up or in the bulletin.",
        "kit_not_live": "Not ready to print yet: the QR code and the web address will appear here once getnovena.app is live.",
        "kit_bulletin_h": "Bulletin insert (about 80 words)",
        "kit_bulletin": "Praying a novena? A novena is nine days of prayer for one intention. Novena, a free-to-start app for Android, holds your place and can send one gentle reminder a day, so day four doesn't slip. It has no ads, no account and no subscription, and what you pray stays on your phone. The full St. Jude novena is at getnovena.app. (Novena is an independent app and is not affiliated with this parish.)",
        "kit_note_h": "A note to hand to a priest or ministry lead",
        "kit_note": [
            "Father, or dear friend in ministry,",
            "I have been using a small Catholic prayer app called Novena and wondered whether it might be worth a line in the bulletin. It helps people pray a novena for all nine days, with a gentle daily reminder. It has no ads, no account and no subscription, and nothing a person prays is sent anywhere. Every prayer in it shows its source.",
            "It is an independent app, not affiliated with any diocese. The full text of the St. Jude novena is free at getnovena.app, if you would like to read it first.",
            "Thank you for considering it.",
        ],
        "kit_poster_line": "Pray a novena,<br>nine days at a time.",
        "kit_poster_sub": "The St. Jude novena, on your phone. Scan to begin.",
        "kit_card_line": "Pray a novena, nine days at a time.",
        "kit_card_sub": "Scan to pray the St. Jude novena",
        "kit_footer": "Novena is an independent app for Android. Not affiliated with any parish, diocese or shrine.",
        # Support
        "support_title": "Support",
        "support_description": "Help with the Novena app: restoring a purchase, reminders, and what happens to your data.",
        "support_contact_h": "Contact",
        "support_contact": "Write to <a href=\"mailto:hello@getnovena.app\">hello@getnovena.app</a>. Please do not send us your prayer intentions; we do not need them to help you, and the app is designed so that we never see them.",
        "support_faq": [
            ("I bought an unlock. How do I get it back on a new phone or after reinstalling?",
             "Open Settings in the app and tap <strong>Restore Purchases</strong>, or tap it on the unlock screen. The app asks Google Play which unlocks your Google account owns and brings them back. Use the same Google account you bought with. If it says it couldn't reach the store, check your connection and try again."),
            ("Why can't you restore my intentions and prayer history?",
             "Because we never have them. Everything you write or pray in Novena is stored only on your phone. There is no account, no server and no cloud backup, so deleting the app, or moving to a new phone, starts you fresh. Your purchases are the exception: Google Play keeps a record of those, so Restore Purchases works."),
            ("My reminder didn't arrive.",
             "Reminders are scheduled on your phone by your phone. Some Android phones stop apps' notifications to save battery. In Android's settings, allow notifications for Novena and exempt it from battery optimisation. Missing a day never resets your progress; the app offers to pick up where you left off."),
            ("Which novenas are free?",
             "Five in each language, with every feature. In English: St. Jude, St. Joseph, St. Anthony of Padua, the Holy Spirit and Our Lady, Undoer of Knots. The free set differs slightly by language. You can filter to free novenas inside the app."),
            ("Is it a subscription?",
             "No. The rest of the catalog is unlocked with a one-time purchase through Google Play. Nothing renews. Google Play shows the price in your currency before you buy."),
            ("Is there an iPhone version?",
             "No. Novena is only on Android."),
            ("Where do the prayers come from?",
             "Each novena shows its source in the app, under Sources & attribution. Some texts are traditional prayers; many reflections were written for the app. Novena is not endorsed by any diocese, parish or shrine."),
            ("Does the app collect any data?",
             "The app has no analytics, no advertising and no tracking, and your intentions and prayers are never sent anywhere. It does go online for two things: each time it opens it checks Expo's update service for new content, and it asks Google Play which purchases you own, at launch, on the unlock screen, and when you buy or restore. The <a href=\"{privacy}\">privacy policy</a> has the details."),
        ],
        "support_rate": "If Novena helps you, a rating on Google Play helps others find it. In the app: Settings, then Rate Novena. The app never asks you to rate it.",
        # Press
        "press_title": "Press kit",
        "press_description": "Logos, screenshots and descriptions of the Novena app, free to use when writing about it.",
        "press_intro": "Everything here may be used to write about Novena. Please keep the images unaltered.",
        "press_one_sentence_h": "In one sentence",
        "press_one_sentence": "Novena is a private, offline Catholic novena app for Android that helps you pray a nine-day novena with one gentle daily reminder, with no subscription, no account and no ads.",
        "press_paragraph_h": "In a paragraph",
        "press_paragraph": "Novena is a Catholic prayer app for Android built around one practice: the novena, nine days of prayer for one intention. It carries 23 novenas in each of five languages (English, Spanish, Brazilian Portuguese, Italian and Filipino), each language with its own catalog. Five novenas in each language are free with every feature, and the rest are a one-time unlock, never a subscription. It works offline, needs no account, shows no ads, and keeps everything a person prays on their own phone: there is no server of its own and no analytics. Every prayer shows its source.",
        "press_facts_h": "Facts",
        "press_facts": [
            ("Platform", "Android. Coming soon to Google Play; not yet publicly available. There is no iPhone version."),
            ("Package", "com.arapleting.novena"),
            ("Languages", "English, Spanish, Portuguese (Brazil), Italian, Filipino"),
            ("Catalog", "23 novenas per language; 5 free in each"),
            ("Price model", "Free to start; one-time unlock; no subscription"),
            ("Data", "No account, no analytics, no ads; prayers and intentions stay on the phone"),
            ("Name", "Novena, said noh-VEE-nuh in English"),
            ("Contact", "<a href=\"mailto:hello@getnovena.app\">hello@getnovena.app</a>"),
        ],
        "press_assets_h": "Images",
        "press_icon": "App icon, 512 × 512 PNG",
        "press_feature": "Feature graphic, 1024 × 500 PNG",
        "press_shot": "Screenshot, 1080 × 1920 PNG",
        "press_brand_h": "Using the name",
        "press_do_h": "Please do",
        "press_do": [
            "Write the name as <strong>Novena</strong>, one word, capital N.",
            "Describe it as an independent app.",
            "Say “one-time unlock” or “no subscription” rather than quoting a price; prices vary by country and Google Play shows the current one.",
        ],
        "press_dont_h": "Please don't",
        "press_dont": [
            "Say or imply that Novena is endorsed by the Church, a diocese, a parish or a shrine. It isn't.",
            "Describe it as available on iPhone. It isn't.",
            "Crop, recolour or redraw the icon.",
        ],
        # 404
        "notfound_title": "Page not found",
        "notfound_body": "This page doesn't exist, or it has moved.",
        "notfound_home": "Go to the home page",
        "notfound_novenas": "See the novenas",
    },
}


# pt-BR: AWAITING NATIVE READ (drafted 2026-09-23). This branch must not merge
# until a native reader signs off in kipster254/novena docs/launch/journal.md.
STRINGS['pt-BR'] = {'html_lang': 'pt-BR', 'og_locale': 'pt_BR', 'nav_novenas': 'Novenas', 'nav_support': 'Ajuda', 'nav_press': 'Imprensa', 'skip': 'Pular para o conteúdo', 'home_title': 'Novena — reze uma novena, nove dias, um de cada vez', 'home_description': 'Um app católico de novenas para Android, tranquilo e que funciona sem internet. Encontre seu santo, reze a novena e não perca o fio com um lembrete diário discreto. Sem assinatura, sem conta, sem anúncios.', 'hero_kicker': 'Um app católico de novenas para Android', 'hero_line': 'Encontre seu santo. Reze a novena.<br>Nove dias, um de cada vez.', 'promise_line': 'Sem assinatura. Sem conta. Sem anúncios. Funciona sem internet.', 'hero_try': 'Reze aqui a novena a São Judas Tadeu', 'hero_try_sub': 'O texto completo dos nove dias está neste site.', 'section_what': 'O que é', 'what_body': ['Uma novena são nove dias de oração por uma única intenção. Os católicos rezam novenas há séculos, e a parte difícil nunca foi encontrar as palavras. É lembrar no quarto dia.', 'O Novena traz o texto completo de cada novena, guarda o ponto onde você parou e, se você quiser, envia um lembrete diário discreto no horário que você escolher. Se perder um dia, seu progresso fica onde estava. Não há sequência para quebrar.'], 'section_promise': 'O que esperar', 'promise_items': [('Suas intenções ficam no seu celular.', 'Suas intenções, seu progresso e os horários dos seus lembretes ficam guardados só no seu aparelho. Não há conta, nem servidor próprio, nem análise de uso, nem publicidade.'), ('Funciona sem internet.', 'Todas as novenas que você pode ler já estão no seu celular. Modo avião não é problema.'), ('Cada oração mostra sua fonte.', 'Toque em Fontes e atribuição em qualquer novena para ver de onde vem o texto.'), ('Nunca terá assinatura.', 'Cinco novenas são gratuitas, com todos os recursos. O restante do catálogo é desbloqueado com uma compra única pelo Google Play. Nada se renova.')], 'section_free': 'Grátis no app', 'free_intro': 'Estas cinco novenas em português são gratuitas, com lembretes, modo escuro, tamanhos de texto e seu histórico de oração. O texto completo delas também está neste site.', 'free_more': 'Ver as 23 novenas em português', 'section_languages': 'Cinco idiomas', 'languages_body': 'A interface do app e as novenas estão disponíveis em inglês, espanhol, português (Brasil), italiano e filipino. Cada idioma tem seu próprio catálogo de 23 novenas, e as cinco novenas gratuitas mudam um pouco de um idioma para outro.', 'section_honest': 'A contrapartida', 'honest_body': 'Como nada fica guardado fora do seu celular, nada pode ser recuperado se você apagar o app. Suas compras voltam com Restaurar compras, mas suas intenções e seu histórico não. Não há backup nem sincronização, de propósito.', 'section_screens': 'Por dentro do app', 'shot_alts': ['A tela Hoje (em inglês): uma novena a Santa Rita de Cássia no dia 1 de 9, marcada «Catching up» (Colocando em dia), com o botão «Pray day one» (Rezar o dia um)', 'A página de uma novena bloqueada no modo claro (em inglês), com o link «Sources & attribution» (Fontes e atribuição)', "A oração de um dia no modo escuro (em inglês): o fim da meditação do dia, a oração final e o botão «Mark today's prayer done» (Marcar a oração de hoje como concluída)"], 'cta_heading': 'Reze com lembretes', 'cta_body': 'O app guarda o ponto onde você parou e, se você quiser, lembra você uma vez por dia durante os nove dias.', 'coming_soon': 'Em breve no Google Play', 'coming_soon_body': 'O Novena ainda não está disponível publicamente no Google Play. Esta página terá o link no dia em que estiver. Não há versão para iPhone.', 'get_it': 'Disponível no Google Play', 'play_trademark': 'Google Play e o logotipo do Google Play são marcas da Google LLC.', 'not_affiliated': 'O Novena é um app independente. Não é filiado a nenhuma diocese, paróquia ou santuário, nem tem o endosso de nenhum deles.', 'footer_privacy': 'Privacidade', 'footer_support': 'Ajuda', 'footer_press': 'Imprensa', 'footer_novenas': 'Novenas', 'footer_no_tracking': 'Este site não usa cookies e não carrega nada de terceiros.', 'novenas_title': 'Novenas', 'novenas_description': 'As 23 novenas em português do app Novena. Cinco são gratuitas, e o texto completo delas está neste site.', 'novenas_intro': 'O catálogo em português tem 23 novenas. Cinco são gratuitas no app e o texto completo delas está aqui. As demais fazem parte do desbloqueio único, e as páginas delas aqui trazem só um resumo.', 'badge_free': 'Grátis', 'badge_unlock': 'No app', 'free_full_text': 'Texto completo neste site', 'for_label': 'Intenções', 'feast_label': 'Festa', 'fixed_label': 'Rezada todo ano a partir de', 'source_label': 'Fonte', 'imprimatur_label': 'Imprimatur', 'about_label': 'Sobre', 'about_source': 'Sobre este texto', 'how_to': 'Reze uma vez por dia durante nove dias: a oração inicial, depois a meditação do dia e então a oração final. Mantenha uma única intenção durante os nove dias.', 'opening_prayer': 'Oração inicial', 'opening_prayer_note': 'Reze esta oração no início de cada dia.', 'closing_prayer': 'Oração final', 'day': 'Dia', 'day_of': 'Dia {n} de 9', 'days_nav': 'Ir para um dia', 'back_to_top': 'Voltar aos dias', 'in_app_heading': 'Reze com lembretes no app', 'in_app_body': 'O app guarda o ponto onde você parou nesta novena e, se você quiser, lembra você uma vez por dia no horário que escolher. Esta novena é gratuita no app, sem conta.', 'summary_note': 'Esta novena faz parte do desbloqueio único do app, por isso o texto dela não é publicado aqui.', 'summary_sources': 'No app, toque em Fontes nesta novena para ver a nota completa sobre as fontes.', 'novena_page_title': '{title} — texto completo, nove dias', 'novena_page_description': 'Reze a {title}: o texto completo dos nove dias, com a fonte e uma nota sobre a origem de cada oração.', 'summary_page_description': '{title} no app Novena para Android: a quem se reza, por quais intenções e de onde vem o texto.', 'saint_label': 'Rezada a', 'other_free': 'Outras novenas gratuitas', 'nav_guide': 'O que é uma novena?', 'guide_title': 'O que é uma novena e como rezar?', 'guide_description': 'Uma novena são nove dias de oração por uma única intenção. De onde vem essa prática, como rezar e cinco novenas que você pode começar hoje.', 'guide_sections': [('Nove dias, uma intenção', ['Uma novena é uma oração feita em nove dias seguidos, normalmente por uma única intenção: uma necessidade que você carrega, uma pessoa que você ama, uma decisão que precisa tomar ou uma ação de graças. A palavra vem do latim <i lang="la">novem</i>, nove.', 'A <i>Catholic Encyclopedia</i> de 1911 a define como «uma devoção de nove dias, privada ou pública, na Igreja Católica, para obter graças especiais», e observa que ela é «permitida e até recomendada pela autoridade eclesiástica, mas ainda não tem um lugar próprio e plenamente estabelecido na liturgia da Igreja» (tradução nossa). Uma novena é uma devoção, não um sacramento nem uma fórmula que garante um resultado.']), ('De onde vêm os nove dias', ['O mesmo artigo chama o primeiro Pentecostes de «o melhor modelo e exemplo» de novena (tradução nossa). Depois da Ascensão, os apóstolos voltaram a Jerusalém e esperaram o Espírito Santo no cenáculo. Os Atos dos Apóstolos dizem: «Todos estes perseveravam unânimes na oração, com as mulheres e com Maria, a mãe de Jesus, e com os irmãos dele» (Atos 1,14, tradução nossa). São Judas é um dos apóstolos nomeados naquela sala: «Judas, irmão de Tiago» (Atos 1,13).', 'Muitas novenas são rezadas nos nove dias antes da festa de um santo, de modo que o último dia cai na véspera da festa ou no próprio dia da festa. Outras são rezadas em qualquer época do ano, sempre que surge a necessidade.']), ('Como rezar', ['Escolha uma intenção e mantenha-a durante os nove dias. Você não precisa escrevê-la nem contá-la a ninguém.', 'Reze uma vez por dia, mais ou menos no mesmo horário, se puder. Cada dia costuma ter uma oração inicial, uma leitura ou meditação breve e uma oração final. Leva poucos minutos.', 'Se perder um dia, continue de onde parou. A prática é a fidelidade, não a perfeição.', 'No fim, muitas pessoas agradecem, seja qual for o resultado, e algumas começam outra novena.'])], 'guide_free_h': 'Cinco novenas para rezar hoje', 'guide_free_intro': 'O texto completo de cada uma está neste site, e elas são gratuitas no app.', 'guide_source': 'Fontes: «Novena», Joseph Hilgers, <i>The Catholic Encyclopedia</i>, vol. 11 (1911, domínio público), newadvent.org/cathen/11141b.htm, citada em tradução nossa; Atos 1,12-14, tradução nossa a partir da Vulgata (domínio público). Ambas consultadas em 23 de setembro de 2026.', 'parish_title': 'Novena: reze uma novena, nove dias, um de cada vez', 'parish_description': 'Você conheceu o Novena por um cartão ou um boletim. Reze aqui a novena a São Judas Tadeu, de graça, ou veja as cinco novenas gratuitas.', 'parish_intro': 'Você chegou aqui por um cartão, um cartaz ou um boletim. Seja bem-vindo. O Novena é um app independente; não é administrado por nenhuma paróquia ou diocese nem filiado a elas, e quem compartilhou este cartão fez isso como amigo.', 'parish_body': 'Uma novena são nove dias de oração por uma única intenção. Você pode rezar aqui mesmo, neste site: o texto completo de cada dia está na página. Se quiser ajuda para lembrar, o app Novena para Android guarda o ponto onde você parou e pode lembrar você uma vez por dia. Não há conta nem anúncios, e nada do que você reza sai do seu celular.', 'parish_start': 'Começar a novena a São Judas Tadeu, dia 1', 'parish_all': 'As cinco novenas gratuitas', 'kit_title': 'Material para paróquias', 'kit_description': 'Um cartaz para imprimir, cartões com QR code e um texto para o boletim, para divulgar o Novena numa paróquia, e um bilhete curto para um padre ou coordenador de pastoral.', 'kit_intro': 'Para quem quiser divulgar o Novena na sua paróquia. Imprima esta página: ela sai como um cartaz, uma folha de cartões e um texto para o boletim. Antes de afixar qualquer coisa ou colocá-la no boletim, fale com a secretaria paroquial.', 'kit_not_live': 'Não imprima ainda. O QR code aponta para getnovena.app, que ainda não está no ar. Este aviso desaparece quando estiver.', 'kit_bulletin_h': 'Texto para o boletim (cerca de 80 palavras)', 'kit_bulletin': 'Vai rezar uma novena? Uma novena são nove dias de oração por uma única intenção. O Novena, um app para Android que você começa a usar de graça, guarda o ponto onde você parou e pode enviar um lembrete discreto por dia, para o quarto dia não passar em branco. Não tem anúncios, nem conta, nem assinatura, e o que você reza fica no seu celular. A novena completa a São Judas Tadeu está em getnovena.app/pt-br. (O Novena é um app independente e não é filiado a esta paróquia.)', 'kit_note_h': 'Um bilhete para entregar a um padre ou coordenador de pastoral', 'kit_note': ['Padre, ou querido irmão na pastoral,', 'Tenho usado um pequeno app católico de oração chamado Novena e pensei que talvez valesse uma linha no boletim. Ele ajuda as pessoas a rezar uma novena durante os nove dias, com um lembrete diário discreto. Não tem anúncios, nem conta, nem assinatura, e nada do que alguém reza é enviado a lugar nenhum. Cada oração mostra sua fonte.', 'É um app independente, não filiado a nenhuma diocese. O texto completo da novena a São Judas Tadeu está disponível de graça em getnovena.app/pt-br, se o senhor quiser ler antes.', 'Obrigado por considerar.'], 'kit_poster_line': 'Reze uma novena,<br>nove dias, um de cada vez.', 'kit_poster_sub': 'A novena a São Judas Tadeu, no seu celular. Aponte a câmera para começar.', 'kit_card_line': 'Reze uma novena, nove dias, um de cada vez.', 'kit_card_sub': 'Aponte a câmera para rezar a novena a São Judas Tadeu', 'kit_footer': 'O Novena é um app independente para Android. Não é filiado a nenhuma paróquia, diocese ou santuário.', 'support_title': 'Ajuda', 'support_description': 'Ajuda com o app Novena: como restaurar uma compra, os lembretes e o que acontece com seus dados.', 'support_contact_h': 'Contato', 'support_contact': 'Escreva para <a href="mailto:hello@getnovena.app">hello@getnovena.app</a>. Por favor, não nos envie suas intenções de oração; não precisamos delas para ajudar você, e o app foi feito para que nunca as vejamos.', 'support_faq': [('Comprei um desbloqueio. Como recupero num celular novo ou depois de reinstalar o app?', 'Abra Configurações no app e toque em <strong>Restaurar compras</strong>, ou toque nessa opção na tela de desbloqueio. O app pergunta ao Google Play quais desbloqueios sua conta Google tem e os traz de volta. Use a mesma conta Google com que você comprou. Se aparecer que não foi possível conectar à loja, verifique sua conexão e tente de novo.'), ('Por que vocês não conseguem recuperar minhas intenções e meu histórico de oração?', 'Porque nunca os temos. Tudo o que você escreve ou reza no Novena fica guardado só no seu celular. Não há conta, nem servidor, nem backup na nuvem, então apagar o app ou trocar de celular faz você começar do zero. Suas compras são a exceção: o Google Play guarda um registro delas, por isso Restaurar compras funciona.'), ('Meu lembrete não chegou.', 'Os lembretes são programados no seu celular, pelo próprio celular. Alguns celulares Android bloqueiam as notificações dos apps para economizar bateria. Nas configurações do Android, permita as notificações do Novena e tire o app da otimização de bateria. Perder um dia nunca zera seu progresso; o app oferece continuar de onde você parou.'), ('Quais novenas são gratuitas?', 'Cinco em cada idioma, com todos os recursos. Em português: São Judas Tadeu, Santo Antônio, São José, Espírito Santo e Nossa Senhora Desatadora dos Nós. O conjunto gratuito muda um pouco de um idioma para outro. No app, você pode filtrar as novenas gratuitas.'), ('É uma assinatura?', 'Não. O restante do catálogo é desbloqueado com uma compra única pelo Google Play. Nada se renova. O Google Play mostra o preço na sua moeda antes da compra.'), ('Existe versão para iPhone?', 'Não. O Novena é só para Android.'), ('De onde vêm as orações?', 'Cada novena mostra sua fonte no app, em Fontes e atribuição. Alguns textos são orações tradicionais; muitas meditações foram escritas para o app. O Novena não tem o endosso de nenhuma diocese, paróquia ou santuário.'), ('O app coleta algum dado?', 'O app não tem análise de uso, nem publicidade, nem rastreamento, e suas intenções e orações nunca são enviadas a lugar nenhum. Ele só se conecta à internet para duas coisas: cada vez que é aberto, consulta o serviço de atualizações da Expo para ver se há conteúdo novo, e pergunta ao Google Play quais compras você tem, ao iniciar, na tela de desbloqueio e quando você compra ou restaura. A <a href="{privacy}">política de privacidade</a> traz os detalhes.')], 'support_rate': 'Se o Novena ajuda você, uma avaliação no Google Play ajuda outras pessoas a encontrá-lo. No app: Configurações e depois Avaliar Novena. O app nunca pede que você o avalie.', 'press_title': 'Kit de imprensa', 'press_description': 'Logotipos, capturas de tela e descrições do app Novena, de uso livre para quem for escrever sobre ele.', 'press_intro': 'Tudo o que está aqui pode ser usado para escrever sobre o Novena. Por favor, não altere as imagens.', 'press_one_sentence_h': 'Em uma frase', 'press_one_sentence': 'O Novena é um app católico de novenas para Android, privado e que funciona sem internet, que ajuda você a rezar uma novena de nove dias com um lembrete diário discreto, sem assinatura, sem conta e sem anúncios.', 'press_paragraph_h': 'Em um parágrafo', 'press_paragraph': 'O Novena é um app católico de oração para Android construído em torno de uma única prática: a novena, nove dias de oração por uma única intenção. Ele traz 23 novenas em cada um de seus cinco idiomas (inglês, espanhol, português do Brasil, italiano e filipino), cada idioma com seu próprio catálogo. Cinco novenas de cada idioma são gratuitas com todos os recursos, e as demais fazem parte de um desbloqueio único, nunca de uma assinatura. Funciona sem internet, não exige conta, não mostra anúncios e mantém tudo o que a pessoa reza no próprio celular: não há servidor próprio nem análise de uso. Cada oração mostra sua fonte.', 'press_facts_h': 'Fatos', 'press_facts': [('Plataforma', 'Android. Em breve no Google Play; ainda não disponível publicamente. Não há versão para iPhone.'), ('Pacote', 'com.arapleting.novena'), ('Idiomas', 'inglês, espanhol, português (Brasil), italiano, filipino'), ('Catálogo', '23 novenas por idioma; 5 gratuitas em cada um'), ('Modelo de preço', 'Grátis para começar; desbloqueio único; sem assinatura'), ('Dados', 'Sem conta, sem análise de uso, sem anúncios; orações e intenções ficam no celular'), ('Nome', 'Novena, como a palavra em português'), ('Contato', '<a href="mailto:hello@getnovena.app">hello@getnovena.app</a>')], 'press_assets_h': 'Imagens', 'press_icon': 'Ícone do app, PNG de 512 × 512', 'press_feature': 'Gráfico de destaque, PNG de 1024 × 500', 'press_shot': 'Captura de tela, PNG de 1080 × 1920', 'press_brand_h': 'Como usar o nome', 'press_do_h': 'Por favor, faça', 'press_do': ['Escreva o nome como <strong>Novena</strong>, uma só palavra, com N maiúsculo.', 'Descreva-o como um app independente.', 'Diga «desbloqueio único» ou «sem assinatura» em vez de citar um preço; os preços variam de país para país e o Google Play mostra o atual.'], 'press_dont_h': 'Por favor, não', 'press_dont': ['Diga nem dê a entender que o Novena tem o endosso da Igreja, de uma diocese, de uma paróquia ou de um santuário. Não tem.', 'Descreva-o como disponível para iPhone. Não está.', 'Corte, mude as cores ou redesenhe o ícone.'], 'notfound_title': 'Página não encontrada', 'notfound_body': 'Esta página não existe ou foi movida.', 'notfound_home': 'Ir para a página inicial', 'notfound_novenas': 'Ver as novenas'}
