"""Interface strings for the site, per language.

English is final. Every other language is a DRAFT and is not published until a
native reader has signed it off (see docs/launch/journal.md in kipster254/novena).
A language is only built when it appears in build.py's LANGS, and only merged
to main after that sign-off is recorded.
"""

STRINGS = {
    "en": {
        "html_lang": "en",
        "og_locale": "en_US",
        "nav_novenas": "Novenas",
        "nav_support": "Support",
        "nav_press": "Press",
        "skip": "Skip to content",
        "home_title": "Novena — pray a novena, nine days at a time",
        "home_description": "A quiet, offline Catholic novena app for Android. Find your saint, pray the novena, and keep your place with a gentle daily reminder. No subscription, no account, no ads.",
        "hero_kicker": "A Catholic novena app for Android",
        "hero_line": "Find your saint. Pray the novena.<br>Nine days, one at a time.",
        "promise_line": "No subscription. No account. No ads. Works offline.",
        "hero_try": "Pray the St. Jude novena here",
        "hero_try_sub": "The full text of all nine days is on this site.",
        "section_what": "What it is",
        "what_body": [
            "A novena is nine days of prayer for one intention. Catholics have prayed them for centuries, and the hard part has never been finding the words. It is remembering on day four.",
            "Novena gives you the full text of each novena, keeps your place, and, if you want one, sends a gentle daily reminder at a time you choose. If you miss a day, your progress stays where it was. There are no streaks to break.",
        ],
        "section_promise": "What to expect",
        "promise_items": [
            ("Your intentions stay on your phone.", "Your intentions, your progress and your reminder times are stored only on your device. There is no account, no server of our own, no analytics and no advertising."),
            ("It works offline.", "Every novena you can read is already on your phone. Airplane mode is fine."),
            ("Every prayer shows its source.", "Tap Sources & attribution on any novena to see where its text comes from."),
            ("No subscription, ever.", "Five novenas are free, with every feature. The rest of the catalog is unlocked with a one-time purchase through Google Play. Nothing renews."),
        ],
        "section_free": "Free in the app",
        "free_intro": "These five English novenas are free, with reminders, dark mode, text sizes and your prayer history. Their full text is also on this site.",
        "free_more": "See all 23 English novenas",
        "section_languages": "Five languages",
        "languages_body": "The app's interface and its novenas are available in English, Spanish, Portuguese (Brazil), Italian and Filipino. Each language has its own catalog of 23 novenas, and the five free novenas differ slightly from one language to another.",
        "section_honest": "The trade-off",
        "honest_body": "Because nothing is stored anywhere but your phone, nothing can be restored if you delete the app. Your purchases come back through Restore Purchases, but your intentions and history do not. There is no backup and no sync, by design.",
        "section_screens": "Inside the app",
        "shot_alts": [
            "The Today screen: a novena to St. Rita of Cascia on day 1 of 9, marked Catching up, with a Pray day one button",
            "A locked novena's page in light mode, with its Sources & attribution link",
            "A day's prayer in dark mode: the end of the day's reflection, the closing prayer, and Mark today's prayer done",
        ],
        "cta_heading": "Pray it with reminders",
        "cta_body": "The app keeps your place and, if you like, reminds you once a day for all nine days.",
        "coming_soon": "Coming soon to Google Play",
        "coming_soon_body": "Novena is not yet publicly available on Google Play. This page will link to it the day it is. There is no iPhone version.",
        "get_it": "Get Novena on Google Play",
        "play_trademark": "Google Play and the Google Play logo are trademarks of Google LLC.",
        "not_affiliated": "Novena is an independent app. It is not affiliated with or endorsed by any diocese, parish or shrine.",
        "footer_privacy": "Privacy",
        "footer_support": "Support",
        "footer_press": "Press",
        "footer_novenas": "Novenas",
        "footer_no_tracking": "This site sets no cookies and loads nothing from anyone else.",
        # Novena pages
        "novenas_title": "Novenas",
        "novenas_description": "All 23 English novenas in the Novena app. Five are free, and their full text is on this site.",
        "novenas_intro": "The English catalog has 23 novenas. Five are free in the app and their full text is here. The rest are part of the one-time unlock, and their pages here give only a summary.",
        "badge_free": "Free",
        "badge_unlock": "In the app",
        "free_full_text": "Full text on this site",
        "for_label": "Intentions",
        "feast_label": "Feast",
        "fixed_label": "Prayed each year from",
        "source_label": "Source",
        "imprimatur_label": "Imprimatur",
        "about_label": "About",
        "about_source": "About this text",
        "how_to": "Pray once a day for nine days: the opening prayer, then the day's reflection, then the closing prayer. Hold one intention through all nine days.",
        "opening_prayer": "Opening prayer",
        "opening_prayer_note": "Pray this at the start of each day.",
        "closing_prayer": "Closing prayer",
        "day": "Day",
        "day_of": "Day {n} of 9",
        "days_nav": "Jump to a day",
        "back_to_top": "Back to the days",
        "in_app_heading": "Pray it with reminders in the app",
        "in_app_body": "The app keeps your place in this novena and, if you like, reminds you once a day at a time you choose. This novena is free in the app, with no account.",
        "summary_note": "This novena is part of the app's one-time unlock, so its text is not published here.",
        "summary_sources": "In the app, tap Sources on this novena to see its full source note.",
        "novena_page_title": "{title} — full text, nine days",
        "novena_page_description": "Pray the {title}: the full text of all nine days, with its source, and a note on where each prayer comes from.",
        "summary_page_description": "{title} in the Novena app for Android: who it is prayed to, what for, and where its text comes from.",
        "saint_label": "Prayed to",
        "other_free": "Other free novenas",
        # Guide
        "nav_guide": "What is a novena?",
        "guide_title": "What is a novena, and how do you pray one?",
        "guide_description": "A novena is nine days of prayer for one intention. Where the practice comes from, how to pray one, and five novenas you can start today.",
        "guide_sections": [
            ("Nine days, one intention", [
                "A novena is a prayer said on nine days in a row, usually for one intention: a need you are carrying, a person you love, a decision you have to make, or thanksgiving. The word comes from the Latin <i lang=\"la\">novem</i>, nine.",
                "The 1911 <i>Catholic Encyclopedia</i> defines it as “a nine days' private or public devotion in the Catholic Church to obtain special graces”, and notes that it is “permitted and even recommended by ecclesiastical authority, but still has no proper and fully set place in the liturgy of the Church.” A novena is a devotion, not a sacrament and not a formula that guarantees an outcome.",
            ]),
            ("Where the nine days come from", [
                "The same article calls the first Pentecost “the best model and example” of a novena. After the Ascension, the apostles returned to Jerusalem and waited in the upper room for the Holy Spirit. The Acts of the Apostles says: “All these were persevering with one mind in prayer with the women, and Mary the mother of Jesus, and with his brethren” (Acts 1:14, Douay-Rheims). St. Jude is one of the apostles named in that room (Acts 1:13).",
                "Many novenas are prayed in the nine days before a saint's feast, so that the last day falls on the eve of the feast or on the feast itself. Others are prayed at any time of year, whenever the need arises.",
            ]),
            ("How to pray one", [
                "Choose one intention and hold it for all nine days. You do not need to write it down or tell anyone.",
                "Pray once a day, at roughly the same time if you can. Each day usually has an opening prayer, a short reading or reflection, and a closing prayer. It takes a few minutes.",
                "If you miss a day, pick up where you left off. The practice is faithfulness, not perfection.",
                "At the end, many people give thanks whatever the outcome, and some begin another novena.",
            ]),
        ],
        "guide_free_h": "Five novenas you can pray today",
        "guide_free_intro": "The full text of each of these is on this site, and they are free in the app.",
        "guide_source": "Sources: “Novena”, Joseph Hilgers, <i>The Catholic Encyclopedia</i>, vol. 11 (1911, public domain), newadvent.org/cathen/11141b.htm; Acts 1:12–14, Douay-Rheims Bible (public domain). Both read 23 September 2026.",
        # Parish
        "parish_title": "Novena: pray a novena, nine days at a time",
        "parish_description": "You found Novena through a card or a bulletin. Pray the St. Jude novena here, free, or see the five free novenas.",
        "parish_intro": "You found this through a card, poster or bulletin. Welcome. Novena is an independent app; it is not run by or affiliated with any parish or diocese, and whoever shared this card did so as a friend.",
        "parish_body": "A novena is nine days of prayer for one intention. You can pray one right here, on this site: every day's full text is on the page. If you want help remembering, the Novena app for Android keeps your place and can remind you once a day. There is no account, no ads, and nothing you pray leaves your phone.",
        "parish_start": "Start the St. Jude novena, day 1",
        "parish_all": "The five free novenas",
        "kit_title": "Parish kit",
        "kit_description": "A printable poster, QR cards and a bulletin insert for sharing Novena in a parish, and a short note for a priest or ministry lead.",
        "kit_intro": "For anyone who wants to share Novena in their parish. Print this page: it comes out as a poster, a sheet of cards and a bulletin insert. Please ask your parish office before putting anything up or in the bulletin.",
        "kit_not_live": "Do not print yet. The QR code points to getnovena.app, which is not live yet. This notice disappears when it is.",
        "kit_bulletin_h": "Bulletin insert (about 80 words)",
        "kit_bulletin": "Praying a novena? A novena is nine days of prayer for one intention. Novena, a free-to-start app for Android, holds your place and can send one gentle reminder a day, so day four doesn't slip. It has no ads, no account and no subscription, and what you pray stays on your phone. The full St. Jude novena is at getnovena.app. (Novena is an independent app and is not affiliated with this parish.)",
        "kit_note_h": "A note to hand to a priest or ministry lead",
        "kit_note": [
            "Father, or dear friend in ministry,",
            "I have been using a small Catholic prayer app called Novena and wondered whether it might be worth a line in the bulletin. It helps people pray a novena for all nine days, with a gentle daily reminder. It has no ads, no account and no subscription, and nothing a person prays is sent anywhere. Every prayer in it shows its source.",
            "It is an independent app, not affiliated with any diocese. The full text of the St. Jude novena is free at getnovena.app, if you would like to read it first.",
            "Thank you for considering it.",
        ],
        "kit_poster_line": "Pray a novena,<br>nine days at a time.",
        "kit_poster_sub": "The St. Jude novena, on your phone. Scan to begin.",
        "kit_card_line": "Pray a novena, nine days at a time.",
        "kit_card_sub": "Scan to pray the St. Jude novena",
        "kit_footer": "Novena is an independent app for Android. Not affiliated with any parish, diocese or shrine.",
        # Support
        "support_title": "Support",
        "support_description": "Help with the Novena app: restoring a purchase, reminders, and what happens to your data.",
        "support_contact_h": "Contact",
        "support_contact": "Write to <a href=\"mailto:hello@getnovena.app\">hello@getnovena.app</a>. Please do not send us your prayer intentions; we do not need them to help you, and the app is designed so that we never see them.",
        "support_faq": [
            ("I bought an unlock. How do I get it back on a new phone or after reinstalling?",
             "Open Settings in the app and tap <strong>Restore Purchases</strong>, or tap it on the unlock screen. The app asks Google Play which unlocks your Google account owns and brings them back. Use the same Google account you bought with. If it says it couldn't reach the store, check your connection and try again."),
            ("Why can't you restore my intentions and prayer history?",
             "Because we never have them. Everything you write or pray in Novena is stored only on your phone. There is no account, no server and no cloud backup, so deleting the app, or moving to a new phone, starts you fresh. Your purchases are the exception: Google Play keeps a record of those, so Restore Purchases works."),
            ("My reminder didn't arrive.",
             "Reminders are scheduled on your phone by your phone. Some Android phones stop apps' notifications to save battery. In Android's settings, allow notifications for Novena and exempt it from battery optimisation. Missing a day never resets your progress; the app offers to pick up where you left off."),
            ("Which novenas are free?",
             "Five in each language, with every feature. In English: St. Jude, St. Joseph, St. Anthony of Padua, the Holy Spirit and Our Lady, Undoer of Knots. The free set differs slightly by language. You can filter to free novenas inside the app."),
            ("Is it a subscription?",
             "No. The rest of the catalog is unlocked with a one-time purchase through Google Play. Nothing renews. Google Play shows the price in your currency before you buy."),
            ("Is there an iPhone version?",
             "No. Novena is only on Android."),
            ("Where do the prayers come from?",
             "Each novena shows its source in the app, under Sources & attribution. Some texts are traditional prayers; many reflections were written for the app. Novena is not endorsed by any diocese, parish or shrine."),
            ("Does the app collect any data?",
             "The app has no analytics, no advertising and no tracking, and your intentions and prayers are never sent anywhere. It does go online for two things: each time it opens it checks Expo's update service for new content, and it asks Google Play which purchases you own, at launch, on the unlock screen, and when you buy or restore. The <a href=\"{privacy}\">privacy policy</a> has the details."),
        ],
        "support_rate": "If Novena helps you, a rating on Google Play helps others find it. In the app: Settings, then Rate Novena. The app never asks you to rate it.",
        # Press
        "press_title": "Press kit",
        "press_description": "Logos, screenshots and descriptions of the Novena app, free to use when writing about it.",
        "press_intro": "Everything here may be used to write about Novena. Please keep the images unaltered.",
        "press_one_sentence_h": "In one sentence",
        "press_one_sentence": "Novena is a private, offline Catholic novena app for Android that helps you pray a nine-day novena with one gentle daily reminder, with no subscription, no account and no ads.",
        "press_paragraph_h": "In a paragraph",
        "press_paragraph": "Novena is a Catholic prayer app for Android built around one practice: the novena, nine days of prayer for one intention. It carries 23 novenas in each of five languages (English, Spanish, Brazilian Portuguese, Italian and Filipino), each language with its own catalog. Five novenas in each language are free with every feature, and the rest are a one-time unlock, never a subscription. It works offline, needs no account, shows no ads, and keeps everything a person prays on their own phone: there is no server of its own and no analytics. Every prayer shows its source.",
        "press_facts_h": "Facts",
        "press_facts": [
            ("Platform", "Android. Coming soon to Google Play; not yet publicly available. There is no iPhone version."),
            ("Package", "com.arapleting.novena"),
            ("Languages", "English, Spanish, Portuguese (Brazil), Italian, Filipino"),
            ("Catalog", "23 novenas per language; 5 free in each"),
            ("Price model", "Free to start; one-time unlock; no subscription"),
            ("Data", "No account, no analytics, no ads; prayers and intentions stay on the phone"),
            ("Name", "Novena, said noh-VEE-nuh in English"),
            ("Contact", "<a href=\"mailto:hello@getnovena.app\">hello@getnovena.app</a>"),
        ],
        "press_assets_h": "Images",
        "press_icon": "App icon, 512 × 512 PNG",
        "press_feature": "Feature graphic, 1024 × 500 PNG",
        "press_shot": "Screenshot, 1080 × 1920 PNG",
        "press_brand_h": "Using the name",
        "press_do_h": "Please do",
        "press_do": [
            "Write the name as <strong>Novena</strong>, one word, capital N.",
            "Describe it as an independent app.",
            "Say “one-time unlock” or “no subscription” rather than quoting a price; prices vary by country and Google Play shows the current one.",
        ],
        "press_dont_h": "Please don't",
        "press_dont": [
            "Say or imply that Novena is endorsed by the Church, a diocese, a parish or a shrine. It isn't.",
            "Describe it as available on iPhone. It isn't.",
            "Crop, recolour or redraw the icon.",
        ],
        # 404
        "notfound_title": "Page not found",
        "notfound_body": "This page doesn't exist, or it has moved.",
        "notfound_home": "Go to the home page",
        "notfound_novenas": "See the novenas",
    },
}
